### ISSUE TITLE
Changing a CSS class name dynamically does not update children props

### ISSUE THREAD

**Issue by sbs-ableton** [Ableton/aqt-stylesheets#10]
When the class name of an Item's parent changes, the styled properties of the child Item are not re-evaluated.

Sample app follows:

```css
/* sample.css */
/* Rectangles inside "green" class rectangles should be green. */
QQuickRectangle.green { color: "green" }
QQuickRectangle.green QQuickRectangle { color: "green" }

/* Rectangles inside "red" class rectangles should be red. */
QQuickRectangle.red { color: "red" }
QQuickRectangle.red QQuickRectangle { color: "red" }
```

```js
// App.qml
import QtQuick 2.4
import Aqt.StyleSheets 1.1

Item {
    width: 600
    height: 600

    StyleEngine {
        stylePath: "."
        styleName: "sample.css"
    }

    Rectangle {

        // When the mouse is pressed inside the Item I expect the whole
        // item to be green. Instead, the inner square remains red while
        // the outer square changes color.
        StyleSet.name: mouseArea.pressed ? "green" : "red"

        anchors.fill: parent
        color: StyleSet.props.color("color")

        Rectangle {
            anchors.centerIn: parent
            width: 200
            height: 200
            color: StyleSet.props.color("color")
        }

        MouseArea {
            id: mouseArea
            anchors.fill: parent
        }
    }
}
```
